Misc updates
hermanator608/ambiance pull request #7
Opened 2024-01-22 02:02 UTC by maggiemay-afk

Several miscellaneous updates: 

- add cursor for animal crossing and earth ambiance categories
- add livestream logo to the ambiance selector (required changes to our Icon component - added params for color and size) 
- new videos and channels
- updated or removed broken video links
- renamed and restructured several subcategories of ambiance

2024-01-22 22:32 UTC, hermanator608 requested changes

2024-01-22 22:32 UTC, hermanator608 commented on src/components/Selector.tsx
> +type Option = { title: string; id: string; group: string; index: number; live: boolean|undefined };
This can be cleaned up by doing:
```
live?: boolean
```
`?` implies that it's optional (can be undefined)

2024-01-24 23:54 UTC, maggiemay-afk commented
Fixed the shorthand for 'live' to be optional 
Please review again! @hermanator608

2024-01-24 23:57 UTC, hermanator608 approved these changes

2024-01-25 02:59 UTC, merged